version: '3.6'

services:

  tests-pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    volumes:
      - ./docker/pg/create-users.sql:/docker-entrypoint-initdb.d/create-users.sql
    ports:
      - $POSTGRES_LOCAL_PORT:5432


  tests-redis:
    image: redis:$REDIS_VERSON
    ports:
      - $REDIS_LOCAL_PORT:6379


  tests-mail:
    image: mailhog/mailhog:v1.0.1
    ports:
      - $MAILHOG_LOCAL_PORT:8025
      - $SMTP_LOCAL_PORT:1025


  tests-config:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    volumes:
      - './swpt_login:/usr/src/app/swpt_login'
      - './tests:/usr/src/app/tests'
    env_file: .env
    environment:
      - 'PYTHONDONTWRITEBYTECODE=1'
      - 'PRIMARY_POSTGRES_URL=postgresql+psycopg://swpt_login:swpt_login@tests-pg:5432/${POSTGRES_DB}'
      - 'REPLICA_POSTGRES_URL=postgresql+psycopg://swpt_login:swpt_login@tests-pg:5432/${POSTGRES_DB}'
      - 'REDIS_URL=redis://tests-redis:6379/0'
      - 'MAIL_SERVER=tests-mail'
      - 'MAIL_PORT=1025'
      - 'MAIL_DEFAULT_SENDER=Swaptacular <no-reply@example.com>'
    command: configure
    depends_on:
      - tests-pg
      - tests-redis
      - tests-mail

  tests-flush:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    volumes:
      - './swpt_login:/usr/src/app/swpt_login'
    env_file: .env
    environment:
      - 'PYTHONDONTWRITEBYTECODE=1'
      - 'PRIMARY_POSTGRES_URL=postgresql+psycopg://swpt_login:swpt_login@tests-pg:5432/${POSTGRES_DB}'
      - 'REPLICA_POSTGRES_URL=postgresql+psycopg://swpt_login:swpt_login@tests-pg:5432/${POSTGRES_DB}'
      - 'REDIS_URL=redis://tests-redis:6379/0'
    command: flush
    depends_on:
      - tests-pg
      - tests-redis
      - tests-mail

