version: '3.6'

services:

  tests-pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    volumes:
      - ./docker/pg/create-users.sql:/docker-entrypoint-initdb.d/create-users.sql
    ports:
      - $POSTGRES_LOCAL_PORT:5432


  tests-config:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    volumes:
      - './swpt_login:/usr/src/app/swpt_login'
    env_file: .env
    environment:
      - 'PYTHONDONTWRITEBYTECODE=1'
      - 'SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://swpt_login:swpt_login@tests-pg:5432/${POSTGRES_DB}'
    command: configure
    depends_on:
      - tests-pg

  tests-flush:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    volumes:
      - './swpt_login:/usr/src/app/swpt_login'
    env_file: .env
    environment:
      - 'PYTHONDONTWRITEBYTECODE=1'
      - 'SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://swpt_login:swpt_login@tests-pg:5432/${POSTGRES_DB}'
    command: flush
    depends_on:
      - tests-pg

