[tool.poetry]
name = "swpt_login"
version = "0.1.0"
description = "Swaptacular micro-service responsible for user's sign up an login"
authors = ["Evgeni Pandurski <epandurski@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pudb = "*"
web-pdb = "*"
gunicorn = "*"
python-json-logger = "^0.1.11"
redis = "^3.5"
requests = "^2.24"
user-agents = "^2.2"
psycopg2-binary = "^2.8"
requests-oauthlib = "^1.3"
flask-mail = "^0.9.1"
flask-migrate = "^2.4"
flask-redis = "^0.4.0"
flask-babel = "^2.0"
flask-env = "^2.0"
flask_signalbus = "^0.5.4"

[tool.poetry.dev-dependencies]
python-dotenv = ">=0.10.1"
flake8 = "^3.7"
pytest-pudb = "^0.7.0"
pytest-dotenv = "^0.4.0"
mypy = "^0.730"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
