serve:
  public:
    cors:
      enabled: true
      allowed_origins:
        - '*'
      allowed_headers:
        - Authorization
        - Content-Type
        - X-Requested-With
      max_age: 86400
  cookies:
    same_site_legacy_workaround: true

log:
  format: json
  level: warn
